config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get  '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users
  resources :questions, only: [:new, :create, :show] do
    member do
      put "qvote", to: "questions#vote"
    end
  	resources :comments, only: [:create], module: :questions
  	resources :answers, only: [:create] do
      member do
        put "avote", to: "answers#vote"
      end
  	  resources :comments, only: [:create], module: :answers
  	end
  end
  resources :answers, only: [:create] do
    member do
      put "avote", to: "answers#vote"
    end
    resources :comments, only: [:create], module: :answers
  end
end

app/models/question.rb
# == Schema Information
#
# Table name: questions
#
#  id         :integer          not null, primary key
#  title      :string
#  content    :text
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Question < ApplicationRecord
  acts_as_votable
  belongs_to :user
  has_many :answers
  has_many :comments, as: :commentable
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :title, presence: true, length: { maximum: 150 }
  validates :content, presence: true
end

app/controllers/questions/comments_controller.rb
class Questions::CommentsController < CommentsController
  before_action :set_commentable

  private
    def set_commentable
      @commentable = Question.find(params[:question_id])
    end
end 

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
	before_action :logged_in_user, only: [:new, :create, :vote]
  
	def new
		@question = Question.new
  end
  
  def create
  	@question = current_user.questions.build(question_params)
  	if @question.save
  	  flash[:success] = "Question created!"
  	  redirect_to @question
  	else
  	  render 'questions/new'
  	end
  end

  def show
    @question = Question.find(params[:id])
  end

  def vote 
    @question = Question.find(params[:id])
    @question.liked_by current_user
    if @question.vote_registered?
      redirect_to :back
    else
      @question.unliked_by current_user
      redirect_to :back
    end
  end 

  private
    def question_params
      params.require(:question).permit(:title, :content)
    end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_question.html.erb
<li id="question-<%= question.id %>">
  <div class="list-group">
    <div class="list-group-item">
      <div class="metrics">
        <div class="votes">
          <div class="mini-counts">
            <span><%= question.get_likes.size %></span>
          </div>
          <div>votes</div>
        </div>
        <div class="answers">
          <div class="mini-counts">
            <span><%= question.answers.count %></span>
          </div>
          <div>answers</div>
        </div>
      </div>
      <div class="summary">
        <div data-turbolinks="false">
          <div class="title">
            <%= link_to question.title, question %>
          </div>
          <div class="info">
            Pregunta de <%= link_to question.user.email, question.user %> Hace <%= time_ago_in_words(question.created_at) %> 
          </div>
        </div>
      </div>
    </div>
  </div>
</li>

app/views/questions/_question_form.html.erb
<div class="col-sm-10 col-sm-offset-1">
  <br>
<%= form_for(@question) do |f| %>
  <h1>Nueva Pregunta</h1>
  <%= render 'shared/error_messages', object: f.object %>
  <%= f.text_field :title, placeholder: "Título...", class: 'form-control' %>
  <%= f.text_area :content, placeholder: "Descripción...", class: 'form-control', rows: '10' %>
  <%= f.submit "Preguntar", class: "btn btn-dark" %>
<% end %>
<div/>

app/views/questions/new.html.erb
<% provide(:title, "Nueva pregunta") %>
<div class="question_form">
  <%= render 'question_form' %>
</div>

app/views/questions/show.html.erb
<% provide(:title, "Question #{@question.id}") %>
<div class="row">
  <div class="col-sm-10 col-sm-offset-1">
    <table class="table questions-view">
      <tbody>
        <tr>
          <td>
            <% if logged_in? && current_user.liked?(@question) %>
              <%= link_to qvote_question_path(@question), method: :put, class: "element-upvote upvote-active" do %>
                <span class="upvote-arrow"></span>
                <span class="upvote-count"><%= @question.get_likes.size %></span>
              <% end %>
            <% else %>
              <%= link_to qvote_question_path(@question), method: :put, class: "element-upvote" do %>
                <span class="upvote-arrow"></span>
                <span class="upvote-count"><%= @question.get_likes.size %></span>
              <% end %>
            <% end %>
          </td>
          <td>
            <h1 class="title left"><%= @question.title %></h1>
            <span class="author">Por <%= @question.user.name %></span>
            <p class="content"><%= markdown(@question.content) %></p>
            <span class="timestamp">
              Publicado hace <%= time_ago_in_words(@question.created_at) %>
            </span>
          </td>
        </tr>
        <tr>
          <td></td>
          <td>
            <div class="comments">
              <h2><%= @question.comments.count %> <span class="glyphicon glyphicon-comment"></span></h2>
              <ul class="list-group">
                <% @question.comments.each do |comment| %>
                  <li class="list-group-item"><span><%= markdown(comment.content) %></span> - <span class="commenter"><%= link_to comment.user.name, comment.user %> Hace <%= time_ago_in_words(comment.created_at) %> </span>
                  </li>
                <% end %>
              </ul>
              <% if logged_in? %>
                <%= form_for [@question, Comment.new] do |f| %>
                  <%= f.text_area :content, class: "form-control", placeholder: "Nuevo comentario" %>
                  <%= f.submit "Comentar", class: "btn btn-default" %>
                <% end %>
              <% end %>
            </div>
          </td>
        </tr>
      </tbody>
    </table>

    <div class="answers-header">
      <h2>Respuestas (<%= @question.answers.count %>)</h2>
    </div>

    <% @question.answers.each do |answer| %>
      <table class="table answers-view">
        <tbody>
          <tr>
            <td>
              <% if logged_in? && current_user.liked?(answer) %>
                <%= link_to avote_answer_path(answer), method: :put, class: "element-upvote upvote-active" do %>
                  <span class="upvote-arrow"></span>
                  <span class="upvote-count"><%= answer.get_likes.size %></span>
                <% end %>
              <% else %>
                <%= link_to avote_answer_path(answer), method: :put, class: "element-upvote" do %>
                  <span class="upvote-arrow"></span>
                  <span class="upvote-count"><%= answer.get_likes.size %></span>
                <% end %>
              <% end %>
            </td>
            <td>
              <p class="content"><%= markdown(answer.content) %></p>
              <span class="timestamp">
                Respuesta por <%= answer.user.name %> Hace <%= time_ago_in_words(answer.created_at) %>
              </span>
            </td>
          </tr>
          <tr>
            <td></td>
            <td>
              <div class="comments">
                <h3><%= answer.comments.count %> <span class="glyphicon glyphicon-comment"></span></h3>
                <ul class="list-group">
                  <% answer.comments.each do |comment| %>
                    <li class="list-group-item"><span><%= markdown(comment.content) %></span> - <span class="commenter"><%= link_to comment.user.name, comment.user %> Hace <%= time_ago_in_words(comment.created_at) %> </span>
                    </li>
                  <% end %>
                </ul>
                <% if logged_in? %>
                  <%= form_for [answer, Comment.new] do |f| %>
                    <%= f.text_area :content, class: "form-control", placeholder: "Nuevo comentario" %>
                    <%= f.submit "Comentar", class: "btn btn-default" %>
                  <% end %>
                <% end %>
              </div>
            </td>
          </tr>
        </tbody>
      </table>
    <% end %>

    <div class="answer-form">
      <% if logged_in? %>
        <h2>Tu Respuesta</h2>
        <%= form_for [@question, @question.answers.build] do |f| %>
          <%= f.text_area :content, class: "form-control", placeholder: "Nueva Respuesta" %>
          <%= f.submit "Responder", class: "btn btn-default" %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>