config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get  '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users
  resources :questions, only: [:new, :create, :show] do
    member do
      put "qvote", to: "questions#vote"
    end
  	resources :comments, only: [:create], module: :questions
  	resources :answers, only: [:create] do
      member do
        put "avote", to: "answers#vote"
      end
  	  resources :comments, only: [:create], module: :answers
  	end
  end
  resources :answers, only: [:create] do
    member do
      put "avote", to: "answers#vote"
    end
    resources :comments, only: [:create], module: :answers
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	before_action :set_ransack
  def home
    if params[:q].present?
      @all_questions = @search.result.paginate(page: params[:page])
    else
      @all_questions = Question.all.paginate(page: params[:page])
    end
  end
  
  private
    def set_ransack
      @search = Question.search(params[:q])
    end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<div class="row">
  <div class="col-sm-10 col-sm-offset-1">
    <br>
    <h1 class="left">Preguntas</h1>
    <%= link_to "Has una Pregunta", new_question_path, class: "btn btn-default new-question" %>
    <%= render 'shared/all_questions' %>
  </div>
</div>