config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get  '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users
  resources :questions, only: [:new, :create, :show] do
    member do
      put "qvote", to: "questions#vote"
    end
  	resources :comments, only: [:create], module: :questions
  	resources :answers, only: [:create] do
      member do
        put "avote", to: "answers#vote"
      end
  	  resources :comments, only: [:create], module: :answers
  	end
  end
  resources :answers, only: [:create] do
    member do
      put "avote", to: "answers#vote"
    end
    resources :comments, only: [:create], module: :answers
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FlowOverstack</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>    
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar navbar-dark bg-dark">
      <div class="container">
        <div class="col-md-6 col-md-offset-3">
          <%= link_to "FlowOverstack", root_path, class: "navbar-brand" %>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="navbar-nav navbar-right">
            <% if logged_in? %>
              <li class="nav-item">
                <%= link_to "Salir", logout_path, method: :delete, class:"nav-link" %>
              </li>
            <% else %>
              <li><%= link_to "Regístrate", new_user_path, class:"nav-link" %></li>
              <li><%= link_to "Ingresar", login_path, class:"nav-link" %></li>
            <% end %>
          </ul>
          <form class="form-inline my-2 my-lg-0" role="search">
            <input type="text" class="form-control mr-sm-2" placeholder="Buscar">
          </form>
        </div>
      </div>
    </nav>

    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>

    </div>
  </body>
</html>